# Variables, data types and operations

Let's start with the very basics of Python. Each programming language relies on **variables** that have a defined **type**. Based on this type you can perform certain **operations**. This is what we will see here.

## Variables

In programming, a variable is a temporary storage location in the memory of the computer which allows to store a value or a data. Each variable has a **name** and a **value**. The name is a reference: it allows to reuse the value several times in the program.

In Python, to create a variable, we use the name of the variable followed by an equal sign (`=`) and the value we want to store. For example, to create a variable named `age` and assign it the value `30`, we use the following syntax:

In [ ]:
age = 36

You can use the **keyword** `print` for displaying the value of the variable that you have created:

In [ ]:
print(age)

36

## Data Types
There are different types of things you can store in a variable, like numbers or words. We call these different types of things "data types."

- Integers (`int`): These are whole numbers, like `1`, `2`, `3`, and so on.
- Floats (`float`): These are numbers with a decimal point, like `1.5` or `3.14159`.
- Strings (`str`): These are words or phrases, like `"Hello, world!"` or `"Python is fun!"`. They are always surrounded by quotes.
- Booleans (`bool`): These are values that are either `True` or `False`.

**Exercise**

In the next box you can create 4 variables with a **meaningful name** and the appropriate data type. The first one will contain your **first name**, the second one **your age**, the third one your **height** (in meters) and the last one **whether you are born in Belgium**.

In [ ]:
name = "Frank"
age = 27
height = 1.82
born = True

In the next box of code you can print the value of each variable that you have created:

In [ ]:
print (name)
print (age)
print (height)
print (born)

Frank
27
1.82
True

We can also explore the type of each of the variables we have created by using the **keyword** `type`. Modify the code below to check the type of each of the variables:

In [ ]:
print(type(age))
print(type(name))
print(type(born))
print(type(height))

<class 'int'>
<class 'str'>
<class 'bool'>
<class 'float'>

It is also possible to modify the value of the variable. All you have to do is assign it a new value, which will automatically overwrite the previous one. Feel free to modify the code below to modify the value of the variables you have created. You can then check the value and type after each change

In [ ]:
age = 27
print(age)
print(type(age))

27
<class 'int'>

## Good practices: naming and code writing conventions
As in many programming languages, to name a variable, some conventions must be respected.

#### 1. The name of the variable must start with a **letter or an underscore**. The variable can not start with a number or a hyphen.         

❌ Bad example :
```py
# Do not do this
2Name = "James"

# Do not do this
-name = "James"

```

✅ Good example :
```py
# Do this
name = "James"

# Do this
_name = "James"

```
#### 2. **Never put space between words.**

❌ Bad example :
```py
# Do not do this
My name = "Odile"
```

✅ Good example :
```py
# DO is
my_name = "Odile"

```

#### 3. No accents on the names of variables. **Use only English**

❌ Bad example :
```py
# Do not do this
prénom = "Odile"
```

✅ Good example :
```py
# Do this
first_name = "Odile"
```

#### 4. **Always give an explicit name** to the variable.

❌ Bad example :
```py
# Do not do this
a = "Odile"

# Do not do this
fstnme = "Odile"

```

✅ Good example :
```py
# Do this
first_name = "Odile"

# Do this
magic_potion = 42

```

### Time to check

Have a look back to the variables you have created here above (your age, weight, name...) and correct them to ensure they fit the Python naming conventions.

## Arithmetic Operators

The basic operations in programming are mathematical operations. They allow you to make calculations from variables and are used exactly as you learned in primary school. The main operations are:

- `+`: addition
- `-`: subtraction
- `*`: multiplication
- `/`: division

You can also use the following operations:

- `//`: floor division (gives your the result of the division without the decimal part) => `5 // 2 = 2`
- `%`: modulo (gives you the remainder when you divide two numbers) => `5 % 2 = 1`
- `**`: exponentiation (raising a number to a power) => `5 ** 2 = 25`

If you execute the following code it will print the result of the operation. You can test some operations to see what it comes out:

In [ ]:
36/6

6.0

In those operations you can also use variables that you have created prior:

In [ ]:
first_number = 3
second_number = 4

first_number + second_number

7

### Let's practice
In the next box, you will compute the BMI of the most famous people in the world (according to [this website](https://www.watson.ch/fr/soci%C3%A9t%C3%A9/cartes%20du%20monde/536739924-voici-la-personne-la-plus-connue-de-chaque-ville-dans-le-monde)): Barack Obama.

Here are some data about him:

- First name: Barack
- Middle name: Hussein
- Last name: Obama
- Date of birth: 04/08/1961
- Age: We let you compute it
- Place of birth: Honolulu
- Nationality: USA
- Height: 187 cm
- Weight: 79 kg

Look on Internet how to calculate the BMI and do it in python by using variables and arithmetic operators

In [27]:
height = 1,87
bmi = 79/(1.87**2)
print(bmi)

22.59143813091595

### Some more practice

For those exercises we ask you to use variables. For the more complex ones, think to the order of operations!

Write Python programs to solve each of those problems:

1. You have 100€ in cash and 1290€ on your bank account. How much money do you have in total?
2. You are in a shop and you would like to buy 12 bottles of water (0.77€ each). How much will it cost?
3. You have paid the 12 bottles in cash. How much money do you have left in total?
4. You have three children and they would like to go in holiday. They ask you 100, 200 and 400€ respectively. What is the average cost of their holidays?
5. Forget, it's too expensive. You decide to go to US instead. Before booking your tickets you check the weather in New York. You see that it's 40°F. Is it hot or cold? You need to check. Use the following formula to convert the temperature in °C: `C = (F - 32) * 5/9` (**Bonus**: find the way to display the rounded result)
6. Oooopsie, it's too cold and too far. You decide to look for another destination in a radius of 1000km. What is the area of the region you are targeting? (**Bonus**: by doing some Google search, find a clean way to instantiate `pi`)
7. Finally you decide to stay here. Thanks to Becode you will become rich so you decide to give your fortune to your children. Since you are fair you will distribute your money evenly, without bother them with pennies. Since you have 3 children:
    - How much will receive each of them?
    - What will remain for you?

In [1]:
[1] # You have 100€ in cash and 1290€ on your bank account. How much money do you have in total?

cash = 100
bank = 1290
print(cash+bank)

1390

In [2]:
[2] # You are in a shop and you would like to buy 12 bottles of water (0.77€ each). How much will it cost?

bottles = 12
price = 0.77
print(bottles*price)

9.24

In [3]:
[3] # You have paid the 12 bottles in cash. How much money do you have left in total?

print((cash+bank)-(bottles*price))

1380.76

In [4]:
[4] # You have three children and they would like to go in holiday. They ask you 100, 200 and 400€ respectively. What is the average cost of their holidays?

child_1 = 100
child_2 = 200
child_3 = 400
print((child_1+child_2+child_3)/3)

233.33333333333334

In [8]:
[5] #Forget, it's too expensive. You decide to go to US instead. Before booking your tickets you check the weather in New York. You see that it's 40°F.
# Is it hot or cold? You need to check. Use the following formula to convert the temperature in °C: C = (F - 32) * 5/9 (Bonus: find the way to display the rounded result)

degree_f = 40
print((degree_f -32)* 5/9)
round((degree_f -32)* 5/9)

4.444444444444445

4

In [16]:
[6] # Oooopsie, it's too cold and too far. You decide to look for another destination in a radius of 1000km. What is the area of the region you are targeting? (Bonus: by doing some Google search, find a clean way to instantiate pi)

from math import pi
area_m = (pi*1000 **2)
area_km = area_m / 100
print(area_km)

31415.926535897932

In [17]:
[7] # Finally you decide to stay here. Thanks to Becode you will become rich so you decide to give your fortune to your children. Since you are fair you will distribute your money evenly, without bother them with pennies. Since you have 3 children:
# How much will receive each of them?
# What will remain for you?

((cash+bank)-(bottles*price))
rest = 1380.76
print(rest/3)
rounded_number = round (rest/3)
print(rounded_number)
child_money = 460
((cash+bank)-(bottles*price))-(child_money*3)

460.25333333333333
460

0.7599999999999909